# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: Research
    url: research/
    weight: 2
  - name: Writing
    url: writing/
    weight: 3
  - name: Note
    url: note/
    weight: 4
  - name: Code
    url: code/
    weight: 5
  - name: Teaching
    url: teaching/
    weight: 6
